### ISSUE TITLE
Steps to execute/modify template

### ISSUE THREAD

**Issue by narendar225** [monken/aws-ecr-public#5]
Hi,
I am looking to make my ECR public. I have basic knowledge with aws(gateway,lambda,cf template). 

All I did was clicked on **Launch Stack** and executed in aws. 

When I tried to hit the GET/HEAD on API gateway, I am getting 404 error. I also tried docker pull on my image from ecr. It complains about docker login.

Are there any other steps do I need to configure like setting up ecr name or IAM policies or any other manual steps on the cloud formation template/js code? 

I really appreciate your help

**Comment by monken** [comment]
What's the name of your repository? Assuming your repository name is `nginx` and you have an image called `alpine`, then you need to use the API Gateway URL to pull (where `v3iomfy255` is your API Gateway's id):

```
docker pull v3iomfy255.execute-api.us-east-2.amazonaws.com/nginx:alpine
```

**Comment by narendar225** [comment]
Earlier I tried directly giving the ecr docker image url. 
After changing as per suggestion,  I am able to execute docker pull command without any issue. Thank you for your yelp :). 
Earlier I was doing aws cli to do ecr login, docker pull. But with this, It is little slow downloading the image from ecr. 
Is it because we are downloading via API Gateway. is this an expected thing?

**Comment by monken** [comment]
It should be the same speed. At the end of the day, you are downloading directly from S3 and not through the API Gateway (see the diagram). Some other factors might have impacted your performance test. Try to pull from an instance within the same AWS region to check the download performance under perfect conditions.

**Comment by narendar225** [comment]
You are right, i tried both from the options (Manual pull from ecr & from the api both are acting same). This might be an issue with from my machine. Thanks for your quick response 👍
