### ISSUE TITLE
Add option to customize which images are public

### ISSUE THREAD

**Issue by millergd** [monken/aws-ecr-public#6]
I'd like to see an option to specify which images this API is allowed to pull. Does it sound reasonable to inject a list into the lambda function file before deploying the CF stack?

**Comment by monken** [comment]
Have you had a look at the FAQ (https://github.com/monken/aws-ecr-public#how-can-i-restrict-access-to-certain-registries)? You can attach a custom policy to the lambda role that would limit the access permissions to specific repositories. The `NotResource` statement is the key here which allows you to deny access to all repositories except the ones mentioned.

**Comment by millergd** [comment]
Perfect! Closing this then. Great work btw!

**Comment by Hobart2967** [comment]
Unfortunately, it doesn't really work for me. I can fully open my repository, but implementing the restriction in the yaml file does not deploy as long as I remove the variables and replace them by "*" for any region and any account id. This will make it deploy, but:

As soon as I try pulling, I only get:

Error response from daemon: denied.

Pulling without the additional config works like a charm. But that is not my aim :D

**Comment by monken** [comment]
Would you mind sharing the part that you modified?

**Comment by Hobart2967** [comment]
Thx for the quick reply. One of the worst situations in IT life: Managed to get it working, but I don't know why it works now :D

Thumbs up for the great work!
