### ISSUE TITLE
Steps to make use of this. When Launching stack always give ROLLBACK_COMPLETE status

### ISSUE THREAD

**Issue by DanWijaya** [monken/aws-ecr-public#9]
Hi I would like to make my ECR public. I am a beginner in AWS. So I am not too sure how can I make use of this except that I do click the create stack under the deploy instructions. 

However when I have done creating it in the aws console, it always give me roolback_complete status, where it seems it does not allow me to launch the stacks. 

Is there some steps required before go to create the stack? I would appreciate your help. Thankyou so much.

**Comment by monken** [comment]
Please try again with the latest version. The previous version had referenced an outdated version of the NodeJS runtime.

**Comment by DanWijaya** [comment]
Hi So I have successfully deployed the stack. Right now I have an ECR created on my console (named my-first-repo). For now it still needs the docker client to get the credentials so that I can push or pull images to ECR. I am pretty sure that I missed sth, but don't know what it is. I tried to access the invoke URL on the API Gateway(both HEAD and GET method) and it gives error. Thank you.

**Comment by monken** [comment]
Please include the error message you are receiving and the request you are executing.

**Comment by DanWijaya** [comment]
It returns 404 notfound 

This 806ycvye8k.execute-api.us-east-2.amazonaws.com page can’t be foundNo webpage was found for the web address: https://806ycvye8k.execute-api.us-east-2.amazonaws.com/Stage/%7Bproxy+%7D
HTTP ERROR 404

**Comment by monken** [comment]
It looks good to me:

```
curl -i  https://806ycvye8k.execute-api.us-east-2.amazonaws.com/v2/
HTTP/2 200
date: Wed, 11 Mar 2020 17:54:54 GMT
content-type: application/json
content-length: 0
x-amzn-requestid: 29cce6d6-db83-4561-9a25-44b1d706b82d
x-amz-apigw-id: JPLdRHQ_iYcFS7g=
x-amzn-trace-id: Root=1-5e6925ee-b012b2a1eedeb7ed7854e651
```

I think you are all set.
